/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ittimfn.sample.poi.read;

import java.io.FileNotFoundException;
import java.io.IOException;

import org.apache.poi.EncryptedDocumentException;

import ittimfn.sample.poi.read.controller.ReadExcelController;

public class App {

    private ReadExcelController controller;

    public void exec(String[] args) throws EncryptedDocumentException, FileNotFoundException, IOException {
        int argsIndex = 0;
        String excelFilePath = args[argsIndex++];
        
        this.controller = new ReadExcelController(excelFilePath);
        System.out.println(this.controller.getModel());
        this.controller.close();
    }

    public static void main(String[] args) throws EncryptedDocumentException, FileNotFoundException, IOException {
        new App().exec(args);
    }
}
